#!/bin/bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

# config
NAME=`basename $0`
CONFIG=`echo $0 | sed -e "s/\/$NAME$/\//"`mybackup.config
IGNORE=`echo $0 | sed -e "s/\/$NAME$/\//"`mybackup.ignore

if [ -r $CONFIG ]
then
  . $CONFIG
fi

# ------ File logging ------------------------------------
exec 1>>$BKPLOGFILE
exec 2>>$BKPLOGFILE

date +'%Y-%m-%d %H:%M:%S ' | tr -d '\n'
echo Backup started

# ------ Cleanup & setup ---------------------------------

if [ ! -d $BKPDIR ]; then
  mkdir -p $BKPDIR
fi

find $BKPDIR/ -mtime +$BKPDAYS  | xargs -l1 rm -f
#rm -f $BKPDIR/*

# ------ Backup process ----------------------------------
date +'%Y-%m-%d %H:%M:%S ' | tr -d '\n'
echo Dump started

DBLIST=`mysqlshow --defaults-file=$MYCONF | egrep -v 'Databases|mysql|(information|performance)_schema|(^\+)' | sed -e 's/^|[ ]*//' | sed -e 's/[ ]*|$//' | tr '\n' ' '`

IGNOREOPTS=`for i in \`cat $IGNORE\`; do echo -n "--ignore-table=$i "; done`

SQLDUMPOPTS="--add-drop-table --lock-tables --complete-insert --quick --quote-names --routines $IGNOREOPTS"

cd $BKPDIR

for i in $DBLIST
do
  date +'%Y-%m-%d %H:%M:%S ' | tr -d '\n'
  echo -n Schema $i...
  OUTFILE=$i`date +'_%Y%m%d%H%M%S'`
  mysqldump --defaults-file=$MYCONF --databases $i $SQLDUMPOPTS | gzip > $BKPDIR/$OUTFILE.sql.gz
  echo done.
done

date +'%Y-%m-%d %H:%M:%S ' | tr -d '\n'
echo Dump completed

# ------ Extra information - grants ----------------------
date +'%Y-%m-%d %H:%M:%S ' | tr -d '\n'
echo -n Grants export...

mysql --defaults-file=$MYCONF --silent --skip-column-names --batch --execute "select concat('\'',User,'\'@\'',Host,'\'') as User from mysql.user" |
  sort |
  while read u; do echo "-- $u"; mysql --defaults-file=$MYCONF --silent --skip-column-names --batch --execute "show grants for $u" | sed 's/$/;/' | sed 's/\\\\//g'; done |
  grep -v root |
  grep -v mysql |
  grep -v debian |
  grep -v ^-- > $BKPDIR/mysql-grants.sql

echo done.

date +'%Y-%m-%d %H:%M:%S ' | tr -d '\n'
echo Backup completed
# --------------------------------------------------------

